-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Eletricidade"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    producao numeric,
    porcentagem numeric,
    CONSTRAINT "Eletricidade_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Energia"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    producao numeric,
    consumo numeric,
    mudanca_anual_consumo numeric,
    mudanca_anual_producao numeric,
    CONSTRAINT "Energia_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Escolaridade"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    porc_sem_escolaridade numeric,
    "porc_primario_alcanÃ§ado" numeric,
    porc_primario_completo numeric,
    "porc_secundario_alcanÃ§ado" numeric,
    porc_secundario_completo numeric,
    "porc_superior_alcanÃ§ado" numeric,
    porc_superior_completo numeric,
    populacao_id integer NOT NULL,
    CONSTRAINT "Escolaridade_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Fonte"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    energia integer,
    eletricidade integer,
    CONSTRAINT "Fonte_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Media_Estudo"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    media_anos_primario numeric,
    media_anos_secundario numeric,
    media_anos_superior numeric,
    media_anos_estudo numeric,
    populacao_id integer NOT NULL,
    CONSTRAINT "Media_Estudo_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Pais"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying COLLATE pg_catalog."default",
    CONSTRAINT "Pais_pkey" PRIMARY KEY (id),
    CONSTRAINT "Pais_nome_key" UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public."Populacao"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ano integer NOT NULL,
    sexo character varying COLLATE pg_catalog."default",
    faixa_etaria character varying COLLATE pg_catalog."default",
    quantidade bigint,
    pais_id integer NOT NULL,
    CONSTRAINT "Populacao_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Producao"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ano integer,
    pais_id integer NOT NULL,
    biocombustivel integer,
    carvao integer,
    solar integer,
    eolica integer,
    gas integer,
    combustivel_fossil integer,
    hidro integer,
    nuclear integer,
    CONSTRAINT "Producao_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Escolaridade"
    ADD CONSTRAINT "Escolaridade_populacao_id_fkey" FOREIGN KEY (populacao_id)
    REFERENCES public."Populacao" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Fonte"
    ADD CONSTRAINT "Fonte_eletricidade_fkey" FOREIGN KEY (eletricidade)
    REFERENCES public."Eletricidade" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Fonte"
    ADD CONSTRAINT "Fonte_energia_fkey" FOREIGN KEY (energia)
    REFERENCES public."Energia" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Media_Estudo"
    ADD CONSTRAINT "Media_Estudo_populacao_id_fkey" FOREIGN KEY (populacao_id)
    REFERENCES public."Populacao" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Populacao"
    ADD CONSTRAINT "Populacao_pais_id_fkey" FOREIGN KEY (pais_id)
    REFERENCES public."Pais" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_biocombustivel_fkey" FOREIGN KEY (biocombustivel)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_carvao_fkey" FOREIGN KEY (carvao)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_combustivel_fossil_fkey" FOREIGN KEY (combustivel_fossil)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_eolica_fkey" FOREIGN KEY (eolica)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_gas_fkey" FOREIGN KEY (gas)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_hidro_fkey" FOREIGN KEY (hidro)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_nuclear_fkey" FOREIGN KEY (nuclear)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_pais_id_fkey" FOREIGN KEY (pais_id)
    REFERENCES public."Pais" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Producao"
    ADD CONSTRAINT "Producao_solar_fkey" FOREIGN KEY (solar)
    REFERENCES public."Fonte" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
