CREATE TABLE "Pais" (
  "id" int PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "Populacao" (
  "id" int PRIMARY KEY,
  "ano" int,
  "sexo" varchar,
  "faixa_etaria" varchar,
  "quantidade" bigint,
  "pais_id" int NOT NULL
);

CREATE TABLE "Escolaridade" (
  "id" int PRIMARY KEY,
  "porc_sem_escolaridade" numeric,
  "porc_primario_alcançado" numeric,
  "porc_primario_completo" numeric,
  "porc_secundario_alcançado" numeric,
  "porc_secundario_completo" numeric,
  "porc_superior_alcançado" numeric,
  "porc_superior_completo" numeric,
  "populacao_id" int NOT NULL
);

CREATE TABLE "Media_Estudo" (
  "id" int PRIMARY KEY,
  "media_anos_primario" numeric,
  "media_anos_secundario" numeric,
  "media_anos_superior" numeric,
  "media_anos_estudo" numeric,
  "populacao_id" int NOT NULL
);

CREATE TABLE "Tipo_Eletricidade" (
  "id" int PRIMARY KEY,
  "tipo" varchar
);

CREATE TABLE "Eletricidade" (
  "id" int PRIMARY KEY,
  "ano" int,
  "pais_id" int NOT NULL,
  "tipo_eletricidade_id" int NOT NULL,
  "producao" numeric,
  "consumo" numeric
);

ALTER TABLE "Populacao" ADD FOREIGN KEY ("pais_id") REFERENCES "Pais" ("id");

ALTER TABLE "Escolaridade" ADD FOREIGN KEY ("populacao_id") REFERENCES "Populacao" ("id");

ALTER TABLE "Media_Estudo" ADD FOREIGN KEY ("populacao_id") REFERENCES "Populacao" ("id");

ALTER TABLE "Eletricidade" ADD FOREIGN KEY ("pais_id") REFERENCES "Pais" ("id");

ALTER TABLE "Eletricidade" ADD FOREIGN KEY ("tipo_eletricidade_id") REFERENCES "Tipo_Eletricidade" ("id");



##modelo lógico:
CREATE TABLE "Pais" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "Tipo_Eletricidade" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar
);

CREATE TABLE "Populacao" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ano" int,
  "sexo" varchar,
  "faixa_etaria" varchar,
  "quantidade" bigint,
  "pais_id" int NOT NULL
);

CREATE TABLE "Escolaridade" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "porc_sem_escolaridade" numeric,
  "porc_primario_alcançado" numeric,
  "porc_primario_completo" numeric,
  "porc_secundario_alcançado" numeric,
  "porc_secundario_completo" numeric,
  "porc_superior_alcançado" numeric,
  "porc_superior_completo" numeric,
  "populacao_id" int NOT NULL
);

CREATE TABLE "Media_Estudo" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_anos_primario" numeric,
  "media_anos_secundario" numeric,
  "media_anos_superior" numeric,
  "media_anos_estudo" numeric,
  "populacao_id" int NOT NULL
);

CREATE TABLE "Eletricidade" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ano" int,
  "producao" numeric,
  "consumo" numeric,
  "pais_id" int NOT NULL,
  "tipo_eletricidade_id" int NOT NULL
);

ALTER TABLE "Populacao" ADD FOREIGN KEY ("pais_id") REFERENCES "Pais" ("id");

ALTER TABLE "Escolaridade" ADD FOREIGN KEY ("populacao_id") REFERENCES "Populacao" ("id");

ALTER TABLE "Media_Estudo" ADD FOREIGN KEY ("populacao_id") REFERENCES "Populacao" ("id");

ALTER TABLE "Eletricidade" ADD FOREIGN KEY ("pais_id") REFERENCES "Pais" ("id");

ALTER TABLE "Eletricidade" ADD FOREIGN KEY ("tipo_eletricidade_id") REFERENCES "Tipo_Eletricidade" ("id");


CREATE INDEX idx_populacao_pais_id ON "Populacao" (pais_id);
CREATE INDEX idx_escolaridade_populacao_id ON "Escolaridade" (populacao_id);
CREATE INDEX idx_media_estudo_populacao_id ON "Media_Estudo" (populacao_id);
CREATE INDEX idx_eletricidade_pais_id ON "Eletricidade" (pais_id);
CREATE INDEX idx_eletricidade_tipo_id ON "Eletricidade" (tipo_eletricidade_id);
